language: php
php:
- 5.6
sudo: false
script: make
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: e8eoO1aTvisirYEp98G+vJOzSlggBEILaRTY0OqgOTDMmJm7hD6EDvNFSlqKgwaZNvZcP7NndbSNyypcSQnKbXg7dbHAlRpQCoVx4gNiLBzF7E9panoWNUXn9qvPE4YS/8TxmQmr4hRhxCWrsRsTlAewSmAwH4pZH59smtEC5cqE0AA0H+Ue2x0Dp0T1jPGueqelXqjOvfnx2BAz8OdcpKsf++CYMIJaH1n1jy07bu1oWA82AGC7GqIw/8OctvKQ84JPOI3X+m7XA0xLEBA9ThcRvaVmIWxanQ5B6TEcKfXzKaSpPNtgh6vQJKD9cw9Lkree35ONu75lkYasF1a5Q9Vwi1dYdwZhYOdoxjfQbQMBKHYZVvKzfwY3H14kPsikX/3Qx0o7LHzlAS5IgtTnlVn/tRmjW4MetmGcgBQoIXH0yXGRshXmd3yNuQistFbo9qAl7yISAWH5IB2b/sLU4SfsDCSrRwairYGzQKwXFLTGG65/9xmdb0eYdSVfe2wNrZ1hYW4EfbqlCTOS4+k39ZCplSztkgnezTsH+ZsUPuvRpQBF8bm/8G2I0PBDfl/apffeHdPTGg6JJbsJrLzucNuMkROi0JvBA+0kssxeR8Cq9l16w/qT610caxlOhcIjJRKsGAyK3+ee77wHRxDZj5POcnQn+OrMi0tq6pOk4tc=
  file: composer/composer.phar
  on:
    repo: yuloh/composer-termux
    tags: true
